version: "2.4"
services:
  batch_exporter:
    image: docker.io/ciscocx/batch_exporter:${DOCKER_TAG}
    network_mode: host
    #restart: always  ## FYI: supervisord is set to exit 0 if one of the processes it manages dies.
    environment:
      - SUPERVISORLOGLEVEL=info
    volumes:
      - batch_collector_data:/data:rw

volumes:
  batch_collector_data: {}
